In [2]:
import numpy as np

In [3]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [4]:
np.zeros((2,6), dtype = int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [5]:
np.random.rand(3)  # 0 İle 1 Arasında İçine Verdiğimiz Parametre Kadar Adette Rastgele Değerler Üretir.

array([0.27611518, 0.61108427, 0.03543773])

In [6]:
np.random.rand(2,4) # Vereceğimiz Parametre İle Çok Boyutlu Dizi De Oluşturabiliriz.

array([[0.1827509 , 0.12868   , 0.09305914, 0.20357729],
       [0.73014275, 0.9772985 , 0.77503627, 0.25410281]])

In [7]:
np.random.rand(2, 3) * 10 # Bu Şekilde Değerler 0 İle 1 Değil , 0 İle 10 Arasında Olacak Ama Bunun Daha Kolay Bir Yolu Da Var.

array([[7.01597061, 2.70860135, 3.67436622],
       [6.29821398, 3.28460991, 2.46110606]])

In [8]:
np.random.randint(15, 50, 5) # Rastgele Bir Array Oluşturmada Kullanılır. Başlangıç Ve Bitiş Değeri , Değer Adedi Parametrelerini Alır.

array([39, 49, 44, 48, 31])

In [9]:
np.random.randint(0, 100, (3,4)) #Çok Boyutlu Array Oluşturmak İstersek, Değer Adedi Yerine (x,y) Şeklinde Parametre Giriyoruz.

array([[12, 76, 25, 39],
       [41, 76, 60, 73],
       [33, 51, 88, 77]])

In [10]:
np.random.randint(0, 50, (4,6))

array([[15, 39,  9,  6, 25,  4],
       [16,  7, 18, 21,  5, 41],
       [20, 14,  9, 21, 28,  1],
       [22, 36, 10, 26, 49,  4]])

In [11]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])

In [12]:
arr2d.ndim #.ndim Metodu , Bir NumPy Array'inin Kaç Boyutlu Olduğunu Gösterir. (num (?) dimension)

2

In [13]:
arr2d.shape #.shape Metodu , Bir Array'in Şeklini (Satır , Sütun) Döndürür. 

(4, 3)

In [14]:
arr3d = np.random.randint(0, 10, (2, 3, 4))

In [15]:
arr3d

array([[[4, 9, 0, 4],
        [7, 5, 0, 2],
        [3, 3, 7, 2]],

       [[0, 6, 5, 2],
        [1, 0, 2, 1],
        [4, 1, 2, 6]]])

In [16]:
arr3d.shape #.shape Metodunun 3 Boyutlu Bir Array Üzerinden Örneği. 2 = Kaç Tane Grup Var ? , 3 = Her Grupta Kaç Satır Var? , 4 = Her Grupta Kaç Sütun Var?

(2, 3, 4)

In [17]:
arr1d = np.random.randint(53, 61, 7, dtype = int)

In [18]:
arr1d = np.arange(53, 61)
arr1d[4]

57

In [19]:
arr = np.random.randint(1, 20, 7)
arr

array([12,  9, 14, 10, 13,  1,  1])

In [20]:
arr.max() # Bir Array'deki En Yüksek Sayıyı Döndürür.

14

In [21]:
arr.min() # Bir Array'deki En Küçük Sayıyı Döndürür.

1

In [22]:
arr.argmax() # Bir Array'deki En Büyük Sayının İndex'ini Döndürür.

2

In [23]:
arr.argmin() # Bir Array'deki En Küçük Sayının İndex'ini Döndürür.

5

In [24]:
arr1 = np.arange(50, 65)
arr1

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [25]:
arr2 = arr1[5:11] # Array'lerde İstediğimiz Değerleri Almamızı Sağlar. Buna "Slicing" Denir. Listelerdeki Mantıkla Aynı.
arr2

array([55, 56, 57, 58, 59, 60])

In [26]:
arr2[-5: ] # Negatif İndex Kullanarak Da Slicing Yapılabilir.

array([56, 57, 58, 59, 60])

In [27]:
arr1[3:10:2] # Slicing Yaparken 3. Bir Parametre Daha Verebiliriz. Bu Parametre, Alacağımız Değerlerin İndex Farkını Gösterir.

array([53, 55, 57, 59])

In [28]:
arr1[2:4] = 19 # Bir Array'da İstediğimiz Bir Kısmı, Başka Bir Sayıyla Değiştirebiliyoruz. Buna "Broadcasting" Deniyor.
arr1           # Bu İşlem, Pandas'ın Temelini Oluşturuyor , Bu İşlemleri Pandas'ta Sütunlara Uyguluyoruz.

array([50, 51, 19, 19, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [29]:
arr3 = np.random.randint(-5, 30, 25) # Bir Örneğin Çözümü
arr3[5: 19]

array([-1, 29, 20, 22, 10, 28, 24,  0, -1, 25,  6, 22, 14,  8])

In [30]:
arr4 = np.arange(0, 10)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr4.dtype # .dtype , Bir Array'in İçindeki Değerlerin Hangi Veri Tipine Ait Olduğunu Söyler.

dtype('int32')

In [34]:
arr5 = np.linspace(50,60,5)
arr5

array([50. , 52.5, 55. , 57.5, 60. ])

In [35]:
arr5.dtype # Array'in İçinde 1 Tane Bile Float Varsa "Float" Döndürür.

dtype('float64')

In [40]:
arr6 = np.array([1.2, 3.4, 5.6, 7.8, 9.0])
arr7 = arr6.astype("int") # .astype() Metodu, Bir Array'in Data Type'ını Değiştirmeye Yarar , Kayıplar Olabilir!
arr7.dtype

dtype('int32')

In [41]:
arr8 = np.array(['5', '7', '19', '1', '22', '99', '4'])
arr9 = arr8.astype("int")
arr9.dtype

dtype('int32')