In [1]:
import numpy as np

In [2]:
#.reshape() Metodu Kullanılırken, Hesaplamak İstemediğimiz Boyutları Otomatik Hesaplattırabiliriz.
# Örneğin 30 Karakterli , 1 Boyutlu Bir Array'imiz Var. Bunu 2 Boyutlu Bir Array Yaparken 5x6 Şeklinde Yazabiliriz.
# Ama Sayı Çok Büyük Olursa , Örneğin 144 Olsun , Bunu 9 x a'lık Bir Matris Şeklinde Yazmak İsteyelim , a'yı Bilmiyorsak ; 
# a Yerine -1 Yazarak Biz Hesaplamadan Otomatik Hesaplatıp Matrisi Oluşturabiliriz. 
# Bunu Boyut Değişikliği Yapacağımız Zaman Çok Kullanacağız. Örnek Üzerinde Görelim : 

arr3d = np.arange(120) # 1 Boyutlu , 120 Elemanlı Bir Array Oluşturduk.
arr3d

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119])

In [3]:
arr3d.reshape(4,5,-1) # Burada 1 Boyutlu Ve 120 Karakterden Oluşan Array'i , 3 Boyutlu Bir Hale Getirmek İstediğimizi Düşünelim.
                      # Boyutları Da (4,5,a) Olsun. Eğer a'yı Hesaplayamazsak Veya Hesaplamak İstemezsek -1 Koyarak Otomatik
                      # Şekilde Matrisi Oluşturabiliyoruz. Ama Karakter Sayısı , Boyutlar Çarpımına Tam Bölünmüyorsa Hata Alırız.

array([[[  0,   1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10,  11],
        [ 12,  13,  14,  15,  16,  17],
        [ 18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29]],

       [[ 30,  31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40,  41],
        [ 42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53],
        [ 54,  55,  56,  57,  58,  59]],

       [[ 60,  61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77],
        [ 78,  79,  80,  81,  82,  83],
        [ 84,  85,  86,  87,  88,  89]],

       [[ 90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101],
        [102, 103, 104, 105, 106, 107],
        [108, 109, 110, 111, 112, 113],
        [114, 115, 116, 117, 118, 119]]])

In [4]:
# Çok Boyutlu Array'leri , 1 Boyutlu Array'e Dönüştürmeye "Flatten" Denir.
# .reshape(-1) Komutuyla Bu İşlemi Gerçekleştirebiliyoruz.
arr2d = np.arange(40).reshape(8,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [5]:
arr2d.reshape(-1) # Bu Şekilde Tek Boyuta İndirebiliyoruz. Bunu Tüm Boyutlara Uygulayabiliriz.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [6]:
# Bir Array'in Elemanlarını Döndürmeye "Iteration" Denir. 
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
for i in arr1: # 1 Boyutlu Array'in Iteration'u.
    print(i)

0
1
2
3
4
5
6
7
8
9


In [8]:
arr2 = np.arange(20).reshape(4,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [9]:
for i in arr2:   # 2 Boyutlu Array'in Iteration'u. Kaç Boyutluysa O Kadar For Döngüsüyle Yapabiliriz.
    for j in i:  # Ama Bu İşlem Yavaştır , Daha Hızlısını Da Göreceğiz. (.nditer())
        print(j)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [10]:
# Çok Boyutlu Array'lerde nditer() Fonsksiyonunu Kullanacağız.
arr3d = np.arange(30).reshape(3,2,5)
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [11]:
for i in np.nditer(arr3d): # Bu Şekilde Defalarca For Döngüsü Kullanmadan Elemanları Gezebiliriz.
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29


In [12]:
arr = np.random.randint(0, 10, 10)
arr

array([7, 4, 9, 6, 8, 6, 5, 1, 3, 4])

In [13]:
arr.sum() # Array'deki Değerlerin Toplamını Döndürür.

53

In [14]:
arr.mean() # Array'daki Değerlerin Ortalamasını Döndürür.

5.3

In [15]:
arr.var() # Array'deki Değerlerin Varyansını Döndürür.

5.21

In [16]:
arr.std() # Array'deki Değerlerin Standart Sapmasını Döndürür. 
          # Standart Sapma , Varyansın Kareköküdür.

2.2825424421026654

In [17]:
np.sqrt(arr) # Array'deki Değerlerin Köklerini Döndürür.

array([2.64575131, 2.        , 3.        , 2.44948974, 2.82842712,
       2.44948974, 2.23606798, 1.        , 1.73205081, 2.        ])

In [18]:
np.sin(arr) # Array'deki Değerlerin Sinüs Değerlerini Döndürür.

array([ 0.6569866 , -0.7568025 ,  0.41211849, -0.2794155 ,  0.98935825,
       -0.2794155 , -0.95892427,  0.84147098,  0.14112001, -0.7568025 ])