In [1]:
import numpy as np 

In [4]:
np.zeros(3, dtype = int)

array([0, 0, 0])

In [10]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [11]:
arr3d[0][0][1]

2

In [15]:
arr2d = np.array([[1, 2, 3] , [4, 5, 6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
np.arange(0, 20, 2) #.arange Metodu , Bir Start Noktası (Dahil) , Bir End Noktası (Dahil Değil!) Ve Aralık Değeri Parametrelerini Alır.

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
np.linspace(50, 100, 21) #.linspace Metodu , Bir Start Noktası (Dahil) , Bir End Noktası (Dahil) Ve Oluşturulacak Değer Sayısı Parametrelerini Alır.

array([ 50. ,  52.5,  55. ,  57.5,  60. ,  62.5,  65. ,  67.5,  70. ,
        72.5,  75. ,  77.5,  80. ,  82.5,  85. ,  87.5,  90. ,  92.5,
        95. ,  97.5, 100. ])

In [26]:
np.logspace(1, 3, 10) #.logspace Metodu , Bir Start Değeri (Dahil) , Bir End Değeri (Dahik) Ve Değer Sayısı Parametrelerini Alır.
                      # 10'luk Tabanda Start Değerinden Başlayarak (10 ** Start Değeri) , 10'luk Tabanda End Değerine Kadar (10 ** End Değeri) , Girilen Değer Sayısı Kadar Sayı Üretir.

array([  10.        ,   16.68100537,   27.82559402,   46.41588834,
         77.42636827,  129.1549665 ,  215.443469  ,  359.38136638,
        599.48425032, 1000.        ])

In [28]:
np.arange(10, 101, 5)

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

In [31]:
np.linspace(0, 1000, 26, dtype = int)

array([   0,   40,   80,  120,  160,  200,  240,  280,  320,  360,  400,
        440,  480,  520,  560,  600,  640,  680,  720,  760,  800,  840,
        880,  920,  960, 1000])

In [32]:
np.zeros(5, dtype = int)

array([0, 0, 0, 0, 0])

In [35]:
np.zeros((2, 3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0]])