In [1]:
import numpy as np

In [2]:
arr3d = np.array([[[4, 9, 0, 4],
        [7, 5, 0, 2],
        [3, 3, 7, 2]],

       [[0, 6, 5, 2],
        [1, 0, 2, 1],
        [4, 1, 2, 6]]])      #1

In [3]:
arr3d.ndim

3

In [4]:
arr1 = np.arange(34 , 115, 6)
arr1 #2

array([ 34,  40,  46,  52,  58,  64,  70,  76,  82,  88,  94, 100, 106,
       112])

In [5]:
arr2 = np.linspace(50, 500, 91)
arr2 #3

array([ 50.,  55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.,
       105., 110., 115., 120., 125., 130., 135., 140., 145., 150., 155.,
       160., 165., 170., 175., 180., 185., 190., 195., 200., 205., 210.,
       215., 220., 225., 230., 235., 240., 245., 250., 255., 260., 265.,
       270., 275., 280., 285., 290., 295., 300., 305., 310., 315., 320.,
       325., 330., 335., 340., 345., 350., 355., 360., 365., 370., 375.,
       380., 385., 390., 395., 400., 405., 410., 415., 420., 425., 430.,
       435., 440., 445., 450., 455., 460., 465., 470., 475., 480., 485.,
       490., 495., 500.])

In [6]:
arr3 = np.logspace(2, 5, 8)
arr3 #4

array([   100.        ,    268.26957953,    719.685673  ,   1930.69772888,
         5179.47467923,  13894.95494373,  37275.93720315, 100000.        ])

In [7]:
arr4 = np.arange(9).reshape(3,3)
arr4 #5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
arr5 = np.zeros((6,6), dtype = int)
arr5 #6

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [9]:
arr6 = np.ones((4,4), dtype = int)
arr6 #7

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [10]:
arr7 = np.eye(8, dtype = int)
arr7 #8

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [11]:
arr8 = np.eye(5, dtype = int) * 3
arr8 #9

array([[3, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 3]])

In [12]:
arr9 = np.random.rand(6)
arr9 #10

array([0.50384759, 0.92705974, 0.00409209, 0.85865631, 0.53737759,
       0.53705857])

In [13]:
arr10 = np.random.randint(50, 100, (5,2))
arr10 
arr10.shape #11

(5, 2)

In [14]:
arr11 = np.random.randint(100, 1000, (2,5,5))
print(arr11)
print(arr1.ndim)
print(arr11.shape) #12

[[[350 369 604 296 312]
  [819 612 459 722 165]
  [282 855 385 407 554]
  [243 684 531 342 494]
  [687 354 346 779 661]]

 [[282 179 204 577 160]
  [169 133 523 949 244]
  [662 629 776 538 249]
  [616 248 940 313 113]
  [831 119 150 485 116]]]
1
(2, 5, 5)


In [15]:
arr12 = np.random.randint(0, 101, 10)
print(arr12)
print(arr12.max())
print(arr12.min())
print(arr12.argmax())
print(arr12.argmin()) #13

[26 39 80 26 94  5 39 34 45  3]
94
3
4
9


In [16]:
arr13 = np.random.randint(300, 501, (2,2,5))
arr13

array([[[448, 422, 469, 455, 473],
        [391, 446, 425, 464, 391]],

       [[416, 320, 302, 450, 447],
        [392, 476, 469, 353, 347]]])

In [17]:
print(arr13[0][1][3]) # Max
print(arr13[1][1][3]) # Min
#14

464
353


In [18]:
arr14 = np.arange(51)
arr14

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [19]:
arr14[20:35] = 500
arr14 #15

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500, 500, 500, 500, 500, 500,
       500, 500, 500, 500, 500, 500, 500, 500, 500,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50])

In [20]:
arr = np.arange(60).reshape(3,4,-1)
print(arr)
print(arr.ndim)
print(arr.shape) 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]
3
(3, 4, 5)


In [21]:
arr = np.arange(30).reshape(3,2,-1)
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [22]:
arr.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [23]:
arr4 = np.linspace(0, 120, 60)
arr4

array([  0.        ,   2.03389831,   4.06779661,   6.10169492,
         8.13559322,  10.16949153,  12.20338983,  14.23728814,
        16.27118644,  18.30508475,  20.33898305,  22.37288136,
        24.40677966,  26.44067797,  28.47457627,  30.50847458,
        32.54237288,  34.57627119,  36.61016949,  38.6440678 ,
        40.6779661 ,  42.71186441,  44.74576271,  46.77966102,
        48.81355932,  50.84745763,  52.88135593,  54.91525424,
        56.94915254,  58.98305085,  61.01694915,  63.05084746,
        65.08474576,  67.11864407,  69.15254237,  71.18644068,
        73.22033898,  75.25423729,  77.28813559,  79.3220339 ,
        81.3559322 ,  83.38983051,  85.42372881,  87.45762712,
        89.49152542,  91.52542373,  93.55932203,  95.59322034,
        97.62711864,  99.66101695, 101.69491525, 103.72881356,
       105.76271186, 107.79661017, 109.83050847, 111.86440678,
       113.89830508, 115.93220339, 117.96610169, 120.        ])

In [24]:
for i in np.nditer(arr4):
    print(i)

0.0
2.0338983050847457
4.067796610169491
6.101694915254237
8.135593220338983
10.169491525423728
12.203389830508474
14.23728813559322
16.271186440677965
18.305084745762713
20.338983050847457
22.3728813559322
24.406779661016948
26.440677966101696
28.47457627118644
30.508474576271183
32.54237288135593
34.57627118644068
36.610169491525426
38.644067796610166
40.67796610169491
42.71186440677966
44.7457627118644
46.77966101694915
48.813559322033896
50.847457627118644
52.88135593220339
54.91525423728813
56.94915254237288
58.983050847457626
61.01694915254237
63.050847457627114
65.08474576271186
67.11864406779661
69.15254237288136
71.1864406779661
73.22033898305085
75.25423728813558
77.28813559322033
79.32203389830508
81.35593220338983
83.38983050847457
85.42372881355932
87.45762711864407
89.4915254237288
91.52542372881355
93.5593220338983
95.59322033898304
97.62711864406779
99.66101694915254
101.69491525423729
103.72881355932203
105.76271186440678
107.79661016949152
109.83050847457626
111.86440

In [25]:
arr = np.random.randint(0, 100, 10)
arr

array([78, 71, 36, 67, 48, 80, 71, 25, 10, 52])

In [27]:
print("Sum Of The Values In The Array: {}".format(arr.sum()))
print("Mean Of The Values In The Array: {}".format(arr.mean()))
print("Max Value Of The Array: {}".format(arr.max()))
print("The Variation Of The Values In The Array: {}".format(arr.var()))
print("The Standart Deviation Of The Values In The Array: {}".format(arr.std()))

Sum Of The Values In The Array: 538
Mean Of The Values In The Array: 53.8
Max Value Of The Array: 80
The Variation Of The Values In The Array: 513.9599999999999
The Standart Deviation Of The Values In The Array: 22.670685918163127


In [28]:
# İki Array'i Birleştirmeyi Öğreneceğiz. Bunu .concatenate() İle Yapıyoruz.
# Bu Fonksiyon Parametre Olarak , Birleştirilecek Array'leri Liste Halinde Alır.
# Birleştirme İşlemleri Satır Ve Sütun Bazlı Olabilir , Belirtmemiz Gerek.
# Belirtmezsek , Default Ayarı Kullanılır. (axis = 0) => Düşey , Satır Bazlı.
# 1 Boyutlu Arrayler , 2 Boyutlu Şekilde (axis = 1) Concate Edilemiyor.
# Hem axis = 0 , Hem De axis = 1 Olması İçin 2 Boyutlu Arrayler Olmalı.
# Kısacası Array'in Boyutu, Axis Kısmından Büyük Olmalı.

In [29]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

np.concatenate([arr1, arr2] , axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [30]:
np.concatenate([arr1, arr2], axis = 1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [31]:
# Stackleme (Yığınlama), Concatenate İşleminin Hemen Hemen Aynısı.
# Tek Farklı , Yeni Bir Eksen / Boyut Üzerinde Yapılmasıdır.
# Yani Boyut Sayısı Artar.

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

np.stack([arr1, arr2], axis = 0)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [33]:
# Stackleme 2 Şekilde Yapılabilir: Horizontal (Yatay) & Vertical (Dikey).
# Horizontal => np.hstack()
# Veritcal => np.vstack()

In [34]:
# NumPy Array'lerinde, İstediğimiz Değerlerin Indexlerini .where() Fonksiyonunu Kullanırız.
# Fonksiyon, Parametre Olarak Bir Condition (Şart) Alır.

arr = np.array([1, 2, 3, 4, 5, 4, 3, 2, 1, 2, 5])
np.where(arr == 2)

(array([1, 7, 9], dtype=int64),)

In [35]:
np.where(arr % 2 == 0)

(array([1, 3, 5, 7, 9], dtype=int64),)

In [39]:
# Son Bölümde Random Modülünün Kullanımına Değinildi. 
# Yeni Olan .choice() Metoduna Bakalım.

np.random.choice(np.arange(10))

3

In [40]:
np.random.choice([1, 2, 3, 4, 5])

2